### ISSUE TITLE
Initial process safe state.vi broken after wizard 

### ISSUE THREAD

**Issue by brbrindle** [LabVIEW-DCAF/DCAF-Project-Templates#63]
![test](https://cloud.githubusercontent.com/assets/20828732/23028595/0b0c7bde-f425-11e6-9b49-691e6c50fcbe.png)

I have confirmed that the initial module creation from the wizard leaves a broken project. If there is multiple results or non-double data type as the only result then the type def does not match, and will result in a broken vi. The type def is marked as Auto updating, but does not update in this case.

to manually fix “Review and update type Def” option on the constant cluster, once you approve it things will go back to normal.

**Comment by pollockm** [comment]
@brbrindle 
Multiple double data type results works on my system (2013 version): 
![image](https://cloud.githubusercontent.com/assets/5288961/23032470/13d33982-f43a-11e6-8199-6278b42f15a4.png)

Mixed data type (bool and dbl) works also:
![image](https://cloud.githubusercontent.com/assets/5288961/23032602/90432522-f43a-11e6-9796-3b4d9bedc1e4.png)

Can you be more specific about what data types were failing for you, and on what LV version?

**Comment by brbrindle** [comment]
LV 2015 SP1 is what I am using due to using a CRIO 903X model requiring 2014 or later.

in every run of the wizard, every one ends up with a -1 as the type def.

**Comment by pollockm** [comment]
Data types used, please?

**Comment by pollockm** [comment]
Ok, I can reproduce an issue with three SGL numbers as processing results in 2015.  I probed into the scripting tool, and it works as expected (adds a constant of the correct name and data type to the cluster).  When opening the typedef, the correct name and data types are in there.  It looks like the new feature from LabVIEW 2014 where we no longer try to automatically resolve typedefs is the root cause.

In LV 2013 (in which DCAF was written), LV will do a 'best effort' pass at updating typedefs that have been altered (for example, by a script that builds a project for you).  This still works in my tests in 2013.  In 2014, LV no longer attempts to do it for you, but instead makes you explicitly make a choice.  This is why the Run arrow is broken (this is the intended behavior).

The best solution I can see is adding the Update from Typedef method to the scripting tool, which essentially resolves that dialog automatically and restores a clean run arrow.  This is not possible until/unless we move DCAF source code to 2014, since that method did not exist in 2013.

**Comment by pollockm** [comment]
Fortunately, we had a version bump to 2014 planned for the next release (~NI Week), so we shouldn't have to deal with this annoyance much longer.

**Comment by pollockm** [comment]
Happy day - discovered that the method does exist in 2013.  I'll test to see if adding it has the desired effect.  If so, we can push a fix in the next release.

**Comment by pollockm** [comment]
Seems to work, but needs to be explicitly called on every instance of the typedef.  We'd need to do the same for all instances of all of the clusters...yuck.

**Comment by pollockm** [comment]
For reference later, this is what I used to reproduce: (SGL and Bool)

![image](https://cloud.githubusercontent.com/assets/5288961/23045486/637ef3ba-f46a-11e6-8330-200a08eab17b.png)

**Comment by dbendele** [comment]
Error:
Type Definition 'data cluster': LabVIEW cannot update from type definition without incorrectly preserving default values.
